import type { FastifyInstance } from 'fastify';
import { getPool, initProject2Db } from './project2-db.js';

function authorized(request: any) {
  const expected = process.env.PROJECT2_ADMIN_TOKEN?.trim();
  return Boolean(expected && request.headers['x-project2-admin-token'] === expected);
  app.post('/api/project2/crm/clients/:id/logs',async(request)=>{await initProject2Db();const id=String((request.params as any).id),b:any=request.body||{};const {rows}=await getPool().query('INSERT INTO project2_training_logs(client_id,program_id,exercise_id,set_number,weight_kg,reps,rpe,duration_seconds,completed,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id,b.program_id||null,b.exercise_id||null,b.set_number==null?null:Number(b.set_number),b.weight_kg==null?null:Number(b.weight_kg),b.reps==null?null:Number(b.reps),b.rpe==null?null:Number(b.rpe),b.duration_seconds==null?null:Number(b.duration_seconds),b.completed!==false,b.note||null]);return{ok:true,log:rows[0]};});
  app.get('/api/project2/crm/clients/:id/progress',async(request)=>{await initProject2Db();const id=String((request.params as any).id);const {rows}=await getPool().query('SELECT * FROM project2_training_logs WHERE client_id=$1 ORDER BY performed_on DESC LIMIT 100',[id]);const rpe=rows.filter(x=>x.rpe!=null).slice(0,4);const avg=rpe.length?rpe.reduce((s,x)=>s+Number(x.rpe),0)/rpe.length:null;const recommendation=avg==null?'Собрать данные по RPE':avg>=9?'Рассмотреть снижение нагрузки':avg<=6?'Рассмотреть увеличение нагрузки':'Сохранить текущую нагрузку';return{ok:true,logs:rows,summary:{average_recent_rpe:avg,recommendation}};});
}

export async function registerProject2Crm(app: FastifyInstance) {
  app.addHook('onRequest', async (request, reply) => {
    if (request.url.startsWith('/api/project2/crm/') && !authorized(request)) return reply.code(401).send({ok:false,error:'Unauthorized'});
  });
  app.get('/api/project2/crm/clients', async()=>{await initProject2Db();const {rows}=await getPool().query('SELECT c.*,(SELECT COUNT(*) FROM project2_programs p WHERE p.client_id=c.id) AS program_count,(SELECT COUNT(*) FROM project2_notes n WHERE n.client_id=c.id) AS note_count FROM project2_clients c ORDER BY c.created_at DESC');return{ok:true,clients:rows};});
  app.get('/api/project2/crm/clients/:id', async(request,reply)=>{await initProject2Db();const id=String((request.params as any).id);const {rows}=await getPool().query('SELECT * FROM project2_clients WHERE id=$1',[id]);if(!rows[0])return reply.code(404).send({ok:false,error:'Client not found'});const [programs,measurements,notes,payments]=await Promise.all([getPool().query('SELECT * FROM project2_programs WHERE client_id=$1 ORDER BY created_at DESC',[id]),getPool().query('SELECT * FROM project2_measurements WHERE client_id=$1 ORDER BY measured_on DESC',[id]),getPool().query('SELECT * FROM project2_notes WHERE client_id=$1 ORDER BY created_at DESC',[id]),getPool().query('SELECT * FROM project2_payments WHERE client_id=$1 ORDER BY created_at DESC',[id])]);return{ok:true,client:rows[0],programs:programs.rows,measurements:measurements.rows,notes:notes.rows,payments:payments.rows};});
  app.post('/api/project2/crm/clients/:id/notes', async(request,reply)=>{await initProject2Db();const id=String((request.params as any).id);const note=String((request.body as any)?.note??'').trim();if(!note)return reply.code(400).send({ok:false,error:'Note is required'});const {rows}=await getPool().query('INSERT INTO project2_notes(client_id,note) VALUES($1,$2) RETURNING *',[id,note]);return{ok:true,note:rows[0]};});
  app.post('/api/project2/crm/clients/:id/measurements', async(request)=>{await initProject2Db();const id=String((request.params as any).id);const b:any=request.body||{};const {rows}=await getPool().query('INSERT INTO project2_measurements(client_id,measured_on,body_weight_kg,body_fat_percent,chest_cm,waist_cm,hips_cm,arm_cm,thigh_cm,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[id,b.measured_on||new Date().toISOString().slice(0,10),b.body_weight_kg||null,b.body_fat_percent||null,b.chest_cm||null,b.waist_cm||null,b.hips_cm||null,b.arm_cm||null,b.thigh_cm||null,b.notes||null]);return{ok:true,measurement:rows[0]};});
  app.post('/api/project2/crm/clients/:id/payments', async(request)=>{await initProject2Db();const id=String((request.params as any).id);const b:any=request.body||{};const {rows}=await getPool().query('INSERT INTO project2_payments(client_id,amount,currency,package_name,sessions_purchased,valid_from,valid_until,comment) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id,Number(b.amount||0),b.currency||'RUB',b.package_name||null,Number(b.sessions_purchased||0),b.currency||'RUB',b.valid_from||null,b.valid_until||null,b.comment||null]).catch(async()=>({rows:[]}));return{ok:true,payment:rows[0]};});
  app.post('/api/project2/crm/clients/:id/programs', async(request)=>{await initProject2Db();const id=String((request.params as any).id);const b:any=request.body||{};const {rows}=await getPool().query('INSERT INTO project2_programs(client_id,name,goal,status,starts_on,ends_on,rationale) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[id,String(b.name||'Новая программа').trim(),b.goal||null,b.status||'draft',b.starts_on||null,b.ends_on||null,b.rationale||null]);return{ok:true,program:rows[0]};});
  app.post('/api/project2/crm/programs/:programId/days', async(request)=>{await initProject2Db();const pid=String((request.params as any).programId);const b:any=request.body||{};const {rows}=await getPool().query('INSERT INTO project2_workout_days(program_id,day_number,title) VALUES($1,$2,$3) RETURNING *',[pid,Number(b.day_number),String(b.title||'Тренировка')]);return{ok:true,day:rows[0]};});
  app.post('/api/project2/crm/days/:dayId/exercises', async(request)=>{await initProject2Db();const did=String((request.params as any).dayId);const b:any=request.body||{};const {rows}=await getPool().query('INSERT INTO project2_exercises(workout_day_id,exercise_name,sets,reps,working_weight_kg,rest_seconds,coach_comment,video_url,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[did,String(b.exercise_name||'Упражнение'),b.sets==null?null:Number(b.sets),b.reps??null,b.working_weight_kg==null?null:Number(b.working_weight_kg),b.rest_seconds==null?null:Number(b.rest_seconds),b.coach_comment??null,b.video_url??null,b.sort_order==null?0:Number(b.sort_order)]);return{ok:true,exercise:rows[0]};});
  app.post('/api/project2/crm/programs/:programId/status', async(request,reply)=>{await initProject2Db();const pid=String((request.params as any).programId);const status=String((request.body as any)?.status||'draft');if(!['draft','review','active','archived'].includes(status))return reply.code(400).send({ok:false,error:'Invalid status'});const {rows}=await getPool().query('UPDATE project2_programs SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[status,pid]);if(!rows[0])return reply.code(404).send({ok:false,error:'Program not found'});if(status==='active')await getPool().query('UPDATE project2_clients SET active_program_id=$1,updated_at=NOW() WHERE id=$2',[pid,rows[0].client_id]);return{ok:true,program:rows[0]};});
  app.get('/api/project2/crm/programs/:programId', async(request)=>{await initProject2Db();const pid=String((request.params as any).programId);const {rows:days}=await getPool().query('SELECT * FROM project2_workout_days WHERE program_id=$1 ORDER BY day_number',[pid]);for(const day of days){const r=await getPool().query('SELECT * FROM project2_exercises WHERE workout_day_id=$1 ORDER BY sort_order,id',[day.id]);day.exercises=r.rows;}return{ok:true,days};});
}