-- FitLife persistent storage for Supabase/Postgres.
-- Apply this migration once to the Supabase project used by the backend.

create table if not exists public.users (
  telegram_id bigint primary key,
  first_name text not null,
  last_name text,
  username text,
  language_code text,
  photo_url text,
  role text not null default 'client' check (role in ('client', 'trainer')),
  goal text check (goal in ('health', 'strength', 'fitness')),
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_history (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  workout_id text not null,
  completed_at timestamptz not null default now()
);

create index if not exists workout_history_user_completed_idx
  on public.workout_history (telegram_id, completed_at desc);

create table if not exists public.trainer_clients (
  client_id bigint primary key references public.users(telegram_id) on delete cascade,
  trainer_id bigint not null references public.users(telegram_id) on delete cascade,
  assigned_at timestamptz not null default now()
);

create index if not exists trainer_clients_trainer_idx
  on public.trainer_clients (trainer_id);

create table if not exists public.client_schedules (
  client_id bigint not null references public.users(telegram_id) on delete cascade,
  day smallint not null check (day between 1 and 7),
  workout_id text,
  assigned_by bigint not null references public.users(telegram_id) on delete restrict,
  assigned_at timestamptz not null default now(),
  primary key (client_id, day)
);

create index if not exists client_schedules_assigned_by_idx
  on public.client_schedules (assigned_by);

-- Backend access is performed with the Supabase service role key.
-- RLS is enabled so these tables are not accidentally exposed through the public API.
alter table public.users enable row level security;
alter table public.workout_history enable row level security;
alter table public.trainer_clients enable row level security;
alter table public.client_schedules enable row level security;

-- Keep updated_at correct for user records modified by the backend.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();
