-- Pavel Fitness quiz and lead funnel.

create table if not exists public.programs (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  pdf_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_results (
  id uuid primary key default gen_random_uuid(),
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  goal text not null check (goal in ('weight_loss', 'muscle_gain', 'fitness', 'strength')),
  location text not null check (location in ('home', 'outdoor', 'gym')),
  experience text not null check (experience in ('beginner', 'returning', 'regular')),
  recommended_program text not null references public.programs(slug),
  source text,
  campaign text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  result_shown_at timestamptz,
  program_requested_at timestamptz,
  program_downloaded_at timestamptz,
  trainer_clicked_at timestamptz
);

create index if not exists quiz_results_telegram_idx on public.quiz_results (telegram_id, started_at desc);
create index if not exists quiz_results_source_campaign_idx on public.quiz_results (source, campaign);

create table if not exists public.funnel_events (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  quiz_result_id uuid references public.quiz_results(id) on delete set null,
  event_name text not null check (event_name in ('START','TEST_STARTED','QUESTION_1','QUESTION_2','QUESTION_3','TEST_COMPLETED','RESULT_SHOWN','PROGRAM_REQUESTED','PROGRAM_DOWNLOADED','TRAINER_CLICKED')),
  source text,
  campaign text,
  created_at timestamptz not null default now()
);

create index if not exists funnel_events_event_idx on public.funnel_events (event_name, created_at desc);
create index if not exists funnel_events_user_idx on public.funnel_events (telegram_id, created_at desc);

alter table public.programs enable row level security;
alter table public.quiz_results enable row level security;
alter table public.funnel_events enable row level security;

insert into public.programs (slug, title, description)
values
  ('full_body_beginner', 'FULL BODY — МИКРОЦИКЛ ДЛЯ НОВИЧКА', 'Стартовая программа для новичка или после перерыва.'),
  ('full_body_home', 'FULL BODY HOME', 'Стартовая программа для тренировок дома.'),
  ('outdoor_full_body', 'OUTDOOR FULL BODY', 'Стартовая программа для тренировок на спортплощадке.'),
  ('three_day_split', '3-DAY SPLIT', 'Трёхдневная программа для регулярных тренировок в зале.')
on conflict (slug) do nothing;
